- docs/resources/snapshot_schedule.md
- examples/resources/powerscale_snapshot_schedule/import.sh
- examples/resources/powerscale_snapshot_schedule/provider.tf
- examples/resources/powerscale_snapshot_schedule/resource.tf
- powerscale/constants/constants.go
- powerscale/helper/snapshot_schedule_helper.go
- powerscale/models/snapshot_schedule.go
- powerscale/provider/provider.go
- powerscale/provider/snapshot_schedule_resource.go
- powerscale/provider/snapshot_schedule_resource_test.go
- Implement Snapshot Schedule Resource
- Add Tests
| |
Snapshot Schedule Resource
> Snapshot Schedule Resource Implementation

- powerscale/helper/snapshot_helper.go
- powerscale/provider/snapshot_resource.go
Shows error for invalid path
Snapshot Resource
> Invalid Path Show valid Error

- powerscale/provider/snapshot_schedule_resource.go
Update validators for optional fields
| |
Snapshot Schedule
> Update validators for optional fields

- powerscale/helper/user_helper.go
Update fields in PowerScale_API_9.5.0.json
| |
```paste below
```
```paste below
```
> Update go-client for PowerScale9.5.

- docs/resources/snapshot.md
- docs/resources/snapshot_schedule.md
- examples/resources/powerscale_snapshot/resource.tf
- examples/resources/powerscale_snapshot_schedule/resource.tf
- powerscale/constants/constants.go
- Add a note that if users want to create snapshots on a specific cadence use snapshot schedule.
- Fix spacing with error message.
Snapshot Resource
> Add Note in Snapshot

- client/client.go
Fix Checkmarx Issue of improper error handling
https://osj-sio-03-prd.cec.lab.emc.com/job/Terraform-Pipelines/job/tf-manual/754/
> Fix Checkmarx Issue

- powerscale/helper/resource_helper.go
Fix Checkmarx Issue of Error Handling
> Fix Checkmarx Issue of Error Handling

- docs/data-sources/quota.md
- docs/resources/quota.md
- powerscale/models/quota.go
- powerscale/provider/quota_datasource.go
- powerscale/provider/quota_resource.go
- Since response doesn't contain related fields, need manual modification
- Fix typo
| |
```paste below
```
```paste below
```
> Fix bug handling optional fields

- docs/resources/networkpool.md
- examples/resources/powerscale_networkpool/resource.tf
- powerscale/helper/helper.go
- powerscale/provider/network_pool_resource.go
- powerscale/provider/network_pool_resource_test.go
Fix network pool copy fields issue when list length is 0
Network Pool
> Fix network pool copy fields issue

- powerscale/provider/provider.go
- powerscale/provider/provider_test.go
- powerscale/provider/subnet_datasource_test.go
- powerscale/provider/subnet_resource_test.go
Improve Helper Coverage
https://osj-sio-03-prd.cec.lab.emc.com/job/Terraform-Pipelines/job/tf-manual/862/AT_20Coverage/
> Improve Helper Coverage

- powerscale/provider/nfs_export_resource.go
Fix the failure while renaming zone name for nfs export
| |
```paste below
```
```paste below
```
> Remove validation of nfs zone

- docs/resources/user.md
- examples/resources/powerscale_user/resource.tf
- powerscale/helper/user_helper.go
- powerscale/provider/user_resource.go
Forbidden change user's sid.
| |
User Resource
All tests for user resource are passed.
> Forbidden change user's sid

- docs/resources/ldap_provider.md
- examples/resources/powerscale_ldap_provider/import.sh
- examples/resources/powerscale_ldap_provider/provider.tf
- examples/resources/powerscale_ldap_provider/resource.tf
- powerscale/constants/constants.go
- powerscale/helper/ldap_provider_helper.go
- powerscale/helper/resource_helper.go
- powerscale/models/ldap_provider.go
- powerscale/provider/ldap_provider_resource.go
- powerscale/provider/ldap_provider_resource_test.go
- powerscale/provider/provider.go
- powerscale/provider/user_group_resource_test.go
Support PowerScale LDAP Provider Resource
| |
LDAP Provider Resource
AT for ldap provider passed:
> Support PowerScale LDAP Provider Resource

- docs/resources/filepool_policy.md
- docs/resources/ldap_provider.md
- examples/resources/powerscale_filepool_policy/import.sh
- examples/resources/powerscale_filepool_policy/provider.tf
- examples/resources/powerscale_filepool_policy/resource.tf
- examples/resources/powerscale_ldap_provider/resource.tf
- powerscale/constants/constants.go
- powerscale/helper/file_pool_policy_helper.go
- powerscale/models/file_pool_policy.go
- powerscale/provider/file_pool_policy_resource.go
- powerscale/provider/file_pool_policy_resource_test.go
- powerscale/provider/ldap_provider_data_source.go
- powerscale/provider/ldap_provider_resource.go
- powerscale/provider/provider.go
Support PowerScale File Pool Policy Resource.
| |
File Pool Policy Resource
AT for file pool policy are passed:
> Support PowerScale File Pool Policy Resource

- docs/resources/cluster_email.md
- examples/resources/powerscale_cluster_email/resource.tf
- powerscale/provider/cluster_email_resource.go
- powerscale/provider/cluster_email_resource_test.go
Fix Nullable Field of Cluster Email
Cluster Email
- [] Unit tests
> Fix Nullable Field of Cluster Email

- docs/resources/accesszone.md
- docs/resources/filesystem.md
- docs/resources/quota.md
- examples/resources/powerscale_accesszone/resource.tf
- powerscale/helper/access_zone_helper.go
- powerscale/helper/file_pool_policy_helper.go
- powerscale/helper/file_system_helper.go
- powerscale/helper/groupnet_helper.go
- powerscale/helper/quota_helper.go
- powerscale/helper/resource_helper.go
- powerscale/helper/snapshot_schedule_helper.go
- powerscale/helper/user_group_helper.go
- powerscale/helper/user_helper.go
- powerscale/provider/access_zone_resource.go
- powerscale/provider/access_zone_resource_test.go
- powerscale/provider/file_system_resource.go
- powerscale/provider/file_system_resource_test.go
- powerscale/provider/quota_resource.go
- powerscale/provider/quota_resource_test.go
- powerscale/provider/snapshot_schedule_resource.go
- powerscale/provider/user_group_resource.go
- powerscale/provider/user_group_resource_test.go
- powerscale/provider/user_resource.go
- powerscale/provider/user_resource_test.go
Bugfix and enhancement from customers:
https://github.com/dell/dell-terraform-providers/issues/9
https://github.com/dell/dell-terraform-providers/issues/10
https://github.com/dell/dell-terraform-providers/issues/11
https://github.com/dell/dell-terraform-providers/issues/12
https://github.com/dell/dell-terraform-providers/issues/13
Solutions:
1. Update Read action to make cluster-side updates invisible to terraform for User, User Groups, Groupnet and Access Zone resources.
2. Remove hard codes of auth providers for Access Zone resource.
3. Add validation for different quota type for Quota resource.
4. Change owner and groups fields to Optional for File System resource. …
> Bugfix and enhancement from customers

- docs/resources/network_rule.md
- powerscale/provider/network_rule_resource.go
Update Network Rule Documentation
- [] Unit tests
> Update Network Rule Doc

- docs/index.md
- docs/resources/accesszone.md
- examples/provider/provider.tf
- examples/resources/powerscale_accesszone/resource.tf
Add multiple providers support sample to documentation.
| |
```paste below
```
```paste below
```
> Add multiple providers support sample to documentation.

- CHANGELOG.md
- README.md
Update Readme and Changelog for V1.2.0
NA
NA
> Update Doc for V1.2.0

- powerscale/provider/ldap_provider_resource.go
Fix Ldap Provider Validator Issue
Ldap Provider
> Fix Ldap Provider Validator Issue

- docs/resources/user_mapping_rules.md
- examples/resources/powerscale_user_mapping_rules/import.sh
- examples/resources/powerscale_user_mapping_rules/provider.tf
- examples/resources/powerscale_user_mapping_rules/resource.tf
- powerscale/constants/constants.go
- powerscale/helper/user_mapping_rules_helper.go
- powerscale/models/user_mapping_rules.go
- powerscale/provider/provider.go
- powerscale/provider/subnet_resource_test.go
- powerscale/provider/user_mapping_rules_resource.go
- powerscale/provider/user_mapping_rules_resource_test.go
Add Support for User Mapping Rules resource.
| |
User Mapping Rules resource.
All AT and UT are passed:
> Add Support for User Mapping Rules resource.

- docs/resources/nfs_export_settings.md
- examples/resources/powerscale_nfs_export_settings/import.sh
- powerscale/helper/nfs_export_settings.go
- powerscale/models/nfs_export_settings.go
- powerscale/provider/nfs_export_settings_resource.go
- powerscale/provider/nfs_export_settings_resource_test.go
Modify import function to include zone name
Add maximum validator for max_file_size
Parse default snapshot value to be acceptable for update API
| |
NFS Export Settings
```paste below
```
```paste below
```
> Address Invalid scenario for nfs export settings

- docs/resources/role.md
- examples/resources/powerscale_role/resource.tf
- powerscale/helper/role_helper.go
- powerscale/provider/role_resource.go
- powerscale/provider/role_resource_test.go
Fix Role Param Mismatch Issue 
Role Resource
> Fix Role Param Mismatch Issue

- docs/resources/quota.md
- powerscale/helper/quota_helper.go
- powerscale/provider/nfs_export_resource_test.go
- powerscale/provider/quota_resource.go
- powerscale/provider/quota_resource_test.go
- powerscale/provider/snapshot_datasource_test.go
- Now update linked attribute only when value is updated
- fix acceptance issue due to default value modification
Activate the linked updated only when it is changed and isolate linking/unlinking action
|https://github.com/dell/dell-terraform-providers/issues/15 |
Quota Resource
```paste below
```
https://osj-sio-03-prd.cec.lab.emc.com/job/Terraform-Pipelines/job/tf-manual/1121/
```paste below
```
> Handle linked issue in Quota

- powerscale/provider/access_zone_resource_test.go
Fix Access Zone Reorder UT
Access Zone
> Fix Access Zone Reorder UT

- .gitignore
- Makefile
- examples/data-sources/powerscale_s3_bucket/data-source.tf
- examples/data-sources/powerscale_s3_bucket/provider.tf
- examples/resources/powerscale_s3_bucket/import.sh
- examples/resources/powerscale_s3_bucket/provider.tf
- examples/resources/powerscale_s3_bucket/resource.tf
- powerscale/constants/constants.go
- powerscale/helper/s3_bucket_helper.go
- powerscale/models/s3_bucket.go
- powerscale/provider/provider.go
- powerscale/provider/s3_bucket_datasource.go
- powerscale/provider/s3_bucket_datasource_test.go
- powerscale/provider/s3_bucket_resource.go
- powerscale/provider/s3_bucket_resource_test.go
S3 Bucket datasource Implementation
S3 Bucket resource Implementation
S3 Bucket Resource
S3 Bucket Datasource
Pipeline AT success: https://osj-sio-03-prd.cec.lab.emc.com/job/Terraform-Pipelines/job/tf-manual/1137/
> S3 bucket Resource/Datasource Implementation 

- CHANGELOG.md
- README.md
Update CHANGELOG and README
| |
CHANGELOG and README
- doc updated for release 1.3.0
> doc update

- powerscale/constants/constants.go
- powerscale/helper/file_system_helper.go
- powerscale/provider/file_system_datasource_test.go
- powerscale/provider/file_system_resource.go
- powerscale/provider/file_system_resource_test.go
bugfix for filesystem with unresolvable GID/UID.
Issue: powerscale provider v1.2.0 resource Filesystem fails to create when UID/GID is not resolvable on cluster
|https://github.com/dell/dell-terraform-providers/issues/16 |
File System Resource
All UT and AT for filesystem are passed:
> Bugfix for file system unresolvable UID/GID

- docs/resources/s3_bucket.md
- examples/resources/powerscale_s3_bucket/resource.tf
- powerscale/helper/s3_bucket_helper.go
- powerscale/provider/s3_bucket_resource.go
- powerscale/provider/s3_bucket_resource_test.go
1. Allow update zone from System to none or none to System. 
2. Fix update issue if create_path is set
s3_bucket_resoure
> Fix s3 bucket update issue

- docs/resources/smb_share_settings.md
- examples/resources/powerscale_smb_share_settings/resource.tf
> smb share settings doc update

- powerscale/provider/namespace_acl_datasource_test.go
> Implement copyright check

- docs/index.md
- examples/provider/provider.tf
Update index.md to add new abridged cases
| |
> Update example usage for release 1.4

- powerscale/provider/smb_share_resource_test.go
| |
```paste below
```
```paste below
```
> Specify ca-timeout in AT

- CHANGELOG.md
- README.md
Update CHANGELOG.md and README.md files
> Update CHANGELOG.md and README.md files

- powerscale/provider/s3_zone_settings_resource_test.go
| |
```paste below
```
```paste below
```
> refactor test s3 zone setting [UT]

- powerscale/provider/s3_global_setting_resource_test.go
- powerscale/provider/s3_zone_settings_resource_test.go
Enabled S3 Global Setting after AT completion for next run 
| |
```paste below
```
```paste below
```
> S3 enabled 

- powerscale/provider/cluster_time_resource_test.go
- powerscale/provider/file_system_datasource_test.go
| |
```paste below
```
```paste below
```
> Fix Test cases

- powerscale/helper/support_assist_helper.go
- powerscale/provider/support_assist_resource.go
- powerscale/provider/support_assist_resource_test.go
PR is raised to add tests and validation for support assist resource
| |
> adding tests and validation for support assist

- powerscale/helper/support_assist_helper.go
- powerscale/helper/synciq_global_settings.go
- powerscale/helper/synciq_policy_schema_datasource.go
- powerscale/helper/synciq_rule_schema_datasource.go
- powerscale/models/support_assist.go
- powerscale/models/synciq_global_settings.go
- powerscale/provider/provider_test.go
- powerscale/provider/synciq_global_settings_datasource.go
- powerscale/provider/synciq_policy_datasource_test.go
- powerscale/provider/synciq_replication_rule_datasource_test.go
| |
SyncIQ policy and rule datasource
```paste below
```
```paste below
```
> SyncIQ Datasource validation bugs fixed

- powerscale/helper/s3_global_setting_helper.go
- powerscale/helper/s3_key_helper.go
- powerscale/provider/s3_global_setting_resource.go
- powerscale/provider/s3_zone_settings_resource.go
S3 Features
| |
```paste below
```
```paste below
```
> fix for s3 feature

- powerscale/provider/s3_key_resource_test.go
| |
```paste below
```
```paste below
```
> added admin user for s3 key test

- go.mod
- go.sum
- powerscale/helper/quota_helper.go
- powerscale/provider/quota_resource.go
- powerscale/provider/quota_resource_test.go
Fix the issue where setting a decimal value for the Quota threshold attribute results in idempotency failure Update mockey dependency
| |
Quota Resource
```paste below
```
```paste below
```
> Fix idempotency isuue about Quota threshold

- powerscale/provider/s3_key_resource.go
| |
```paste below
```
```paste below
```
> added space regex validator

- powerscale/helper/support_assist_helper.go
- powerscale/models/support_assist.go
- powerscale/provider/support_assist_resource.go
- powerscale/provider/support_assist_resource_test.go
PR is raised to fix the bugs for support assist resource
support_assist
> fixed bugs for support assist resource

- powerscale/provider/cluster_identity_resource.go
- powerscale/provider/cluster_snmp_resource.go
- powerscale/provider/cluster_snmp_resource_test.go
| |
```paste below
```
```paste below
```
> cluster identity and cluster snmp issues fixed

- powerscale/provider/provider_test.go
| |
```paste below
```
```paste below
```
> Fix checkmarx

- docs/resources/quota.md
- powerscale/helper/quota_helper.go
- powerscale/provider/quota_resource.go
Now not setting threshold percent data as response since PAPI might return inconsistent result due to accuracy loss
Percent threshold can be calculated by actual threshold
| |
```paste below
```
```paste below
```
> Fix issue caused by Quota threshold inconsistency

- CHANGELOG.md
- README.md
| |
```paste below
```
```paste below
```
> Change Log v1.5.0

- powerscale/provider/ads_provider_datasource_test.go
- powerscale/provider/cluster_time_resource_test.go
| |
```paste below
```
```paste below
```
> Cluster Time  test case change

- powerscale/provider/writable_snapshots_resource_test.go
A small PR for UT issue fix in Powerscale
> writable snapshot test fix

- powerscale/provider/writable_snapshot_datasource_test.go
- powerscale/provider/writable_snapshots_resource_test.go
> Added mockey release in writable snapshot tests

- powerscale/helper/network_pool_helper.go
- powerscale/helper/network_rule_helper.go
- powerscale/helper/ntp_server_helper.go
- powerscale/helper/quota_helper.go
- powerscale/helper/role_helper.go
- powerscale/helper/snapshot_helper.go
- powerscale/helper/snapshot_schedule_helper.go
Adding support for getting all paginated data in existing datasources. Priorly datasources got only results from the first page.
> Adding support for getting all paginated data in existing datasources

- powerscale/provider/network_pool_resource_test.go
| |
```paste below
```
```paste below
```
> Formatting for last commit

- docs/resources/writable_snapshot.md
- examples/resources/powerscale_writable_snapshot/resource.tf
| |
```paste below
```
```paste below
```
> Example updated for writable snapshot

- docs/data-sources/groupnet.md
- examples/data-sources/powerscale_groupnet/data-source.tf
- powerscale/helper/groupnet_helper.go
- powerscale/models/groupnet.go
- powerscale/provider/groupnet_data_source.go
Added filters for Groupnet Datasource
Groupnet Datasource
> Added filters for Groupnet Datasource

- powerscale/provider/nfs_export_datasource.go
- powerscale/provider/quota_datasource.go
PR is raised to fix filter issue in NFS export and Quota datasource.
powerscale_quota
powerscale_nfs_export
```
> added fix for nfs export/quota datasource filter issue

- powerscale/provider/nfs_alias_datasource.go
- powerscale/provider/snapshot_schedule_datasource.go
- powerscale/provider/subnet_datasource.go
| |
```paste below
```
```paste below
```
> Filter Validation for NFS Alias, Subnet and Snapshot Schedule Datasource

- powerscale/provider/snapshot_restore_resource.go
PR is raised to fix the bug while updating state file.
```
> bugfix for snapshot restore

- powerscale/helper/role_helper.go
> Role Datasource bugfix

- powerscale/provider/file_system_resource_test.go
- powerscale/provider/s3_bucket_datasource_test.go
PR is raised to update overwrite flag in acceptance tests of filesystem resource.
> updating overwrite flag for filesystem

- powerscale/provider/synciq_policy_datasource_test.go
- powerscale/provider/synciq_replication_reports_datasource_test.go
Adding PreReqs for Replication Report AT
SyncIQ Replication Report Datasource
> Adding PreReqs for Replication Report AT

- powerscale/provider/access_zone_resource_test.go
- powerscale/provider/file_system_datasource_test.go
- powerscale/provider/namespace_acl_datasource_test.go
- powerscale/provider/nfs_export_resource_test.go
- powerscale/provider/snapshot_datasource_test.go
- powerscale/provider/snapshot_resource_test.go
- powerscale/provider/snapshot_schedule_datasource_test.go
- powerscale/provider/snapshot_schedule_resource_test.go
Adding File System Prereqs to dependent resources
FileSystem, NamespaceAcl, Snapshot, SnapshotSchedule
> Adding File System Prereqs to dependent resources

- powerscale/provider/quota_datasource_test.go
- powerscale/provider/quota_resource_test.go
- powerscale/provider/s3_bucket_datasource_test.go
- powerscale/provider/s3_bucket_resource_test.go
- powerscale/provider/smb_share_data_source_test.go
- powerscale/provider/smb_share_resource_test.go
Added filesystem prereqs for dependent resources
Quota, SmbShare, S3Bucket
> Added filesystem prereqs for dependent resources

- client/client.go
- Fix nil pointer issue when there is an invalid password
Before this fix the output for invalid password looked like this
```
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ConfigureProvider call. The plugin logs may contain more details.
╵
Stack trace from the terraform-provider-powerscale_v1.6.0.exe plugin:
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x196fabb]
goroutine 54 [running]:
dell/powerscale-go-client.(*APIClient).GetConfig(...)
dell/powerscale-go-client@v0.0.0/client.go:478...
Error: The terraform-provider-powerscale_v1.6.0.exe plugin crashed!
```
New error when invalid password is set
```
Planning failed. Terraform encountered an …
```
> Handle Invalid Password Gracefully

- catalog-info.yaml
- powerscale/helper/cluster_email_helper.go
- powerscale/helper/helper.go
- powerscale/helper/support_assist_helper.go
- powerscale/provider/cluster_email_resource.go
Updated cluster email API to support new version of PowerScale array.
| |
cluster_email_resource
```paste below
```
> Cluster email update

- powerscale/provider/nfs_alias_datasource_test.go
- powerscale/provider/provider_test.go
- powerscale/provider/storagepool_tier_datasource_test.go
Added minor changes to fix failing test cases
> Added minor changes to fix failing test cases

- powerscale/provider/cluster_email_datasource.go
- powerscale/provider/cluster_email_datasource_test.go
> clusterEmail Datasource fixed

- powerscale/provider/cluster_email_datasource_test.go
> Cluster email UT fixed

- powerscale/helper/role_helper.go
- powerscale/provider/role_resource.go
PR is raised to add validation to the role resource
role resource
```paste below
> adding validation while adding members in role resource

- CHANGELOG.md
- README.md
- docs/index.md
- examples/provider/provider.tf
| |
```paste below
```
```paste below
```
> update doc v1.7.1

- powerscale/helper/smb_share_helper.go
Since PowerScale can return 409 error when concurrent updates happen, add mutex to avoid
|https://github.com/dell/dell-terraform-providers/issues/35 |
SMB share
> Fix concurrent issue of SMB share update
